version: "3"
services:
  navidrome:
    image: registry.cn-shenzhen.aliyuncs.com/lipaysam/navidrome:0.53.2
    ports:
      - "4533:4533"   # 左边可以改成自己服务器未被占用的端口
    environment:
      # Optional: put your config options customization here. Examples(这些都是可选的):
      ND_SCANSCHEDULE: 1m
      ND_LASTFM_ENABLED:
      ND_LASTFM_APIKEY: 3790b6aa4f5480b5156e6944xxxxxxxx # 修改成自己的APIKEY
      ND_LASTFM_SECRET: 7b9dc58f65068200f0644778xxxxxxxx  # 修改成自己的SECRET
      ND_SPOTIFY_ID: 1e88895876f74e7f8a315fexxxxxxxxxxxx  # 修改成自己的ID
      ND_SPOTIFY_SECRET: 1e772d901c1841f49ddxxxxxxxxxxxx # 修改成自己的SECRET
      ND_ENABLETRANSCODINGCONFIG: true   # 设置为 true 才能支持转码功能
      ND_TRANSCODINGCACHESIZE: 100MB   # 转码缓存的大小。设置 0 为禁用缓存，默认为 100MB
      ND_LASTFM_LANGUAGE: en
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "data:/data"
      - "/opt/navidrome/music:/music:ro"  # 冒号左边修改成自己本地的音乐文件夹路径

  filebrowser:
    image: registry.cn-shenzhen.aliyuncs.com/lipaysam/filebrowser:v2
    ports:
      - 8080:80
    profiles:
      - with-deps
    environment:
      - PUID=0
      - PGID=0
    depends_on:
      - navidrome
    volumes:
      - "/opt/filebrowser/database.db:/database.db"
      - "/opt/navidrome/music:/srv"  # 冒号左边修改成自己本地的音乐文件夹路径
    restart: unless-stopped
volumes:
  data: